### ISSUE TITLE
Installation on Ubuntu v7.4.0, 45d PetaSan Version 2.7.3-45drives1

### ISSUE THREAD

**Issue by spraus** [45Drives/tools#20]
Hi all,
I just wanted to report an installation issue with the Ubuntu 7.4.0 that is shipped with PetaSan version 2.7.3. It seems that a required package "smartmontools" is limited to version 6.5 on the release though 45drives-tools required >=7.0.

I hope im doing something wrong though I have tried everything short of recompiling smartmontools manually and installing it.
Thanks;
SPraus

`>sudo apt install 45drives-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 45drives-tools : Depends: smartmontools (>= 7.0) but 6.5+svn4324-1ubuntu0.1 is to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by spraus** [comment]
Im an idiot and I will close this issue as I did not see the requirement for Ubuntu 20.x... Unfortunatly at the current time I dont think that 45drives petasan release supports 20.x.
Sorry about that and thanks!

**Comment by bkelly16** [comment]
Hey @spraus 

We built 45drives-tools for ubuntu18.04. Deb package is [here](http://images.45drives.com/petasan/45drives-tools_1.9.1-1bionic_amd64.deb)
However you will still need smartmontools =>7.0.
This can be done by installing the [deb package manually](http://images.45drives.com/petasan/smartmontools_7.0-0ubuntu1_ubuntu18.04.1_amd64.deb) or enabling bionic-backports in the sources.list file.

We are wokring with petasan to get these packages included in the petasan repos, but this workaround will suffice in the meantime.

I'll leave this issue open in case you run into any issues.

**Comment by markdhooper** [comment]
We have added Ubuntu18.04 builds for 45drives-tools and have performed some preliminary testing using petasan.
These are hosted on our [official repository](repo.45drives.com)

We additionally have the bionic-backports version of [smartmontools](https://repo.45drives.com/debian/pool/main/s/smartmontools/smartmontools_7.0-0ubuntu1~ubuntu18.04.1_amd64.deb) hosted there to provide the dependency that you need for 45drives-tools without having to enable the bionic-backports repo if you don't want/need to.

You can run our [setup script](https://repo.45drives.com/setup.html) to enable our official repository. You may require the lsb-core package for this setup script to run/detect your OS properly as petasan is pretty stripped down. `apt install -y lsb-core`

If you just want the latest 45drives-tools package by itself [45drives-tools_2.0.3-12bionic_amd64.deb](https://repo.45drives.com/debian/pool/main/4/45drives-tools/45drives-tools_2.0.3-12bionic_amd64.deb)
