### ISSUE TITLE
wipedev -a does not wipe drive in slot 1-1.  

### ISSUE THREAD

**Issue by mmcphee** [45Drives/tools#22]
"/opt/45drives/tools/wipedev -a" does not wipe drive in slot 1-1. If we change the initial value of "j" from 3 to 2 it seems to work. 

> if [ $ALL_FLAG -eq 1 ];then
        BAYS=$((cat $CONFIG_PATH/vdev_id.conf| awk "NR>1" | wc -l) 2>/dev/null)
        i=0
        **j=2**
        ## LOOP THROUGH BAYS
        while [ "$i" -lt $BAYS ];do
                bay=$(cat $CONFIG_PATH/vdev_id.conf | awk -v j=$j 'NR==j{print $2}')
                BAY[$i]=$bay
                let i=i+1
                let j=j+1
        done

**Comment by joshuaboud** [comment]
Fixed with #23, thanks Mike for the patch
